"""initial migration

Revision ID: 9740f4dfc4f4
Revises: 
Create Date: 2024-07-26 08:59:59.052590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9740f4dfc4f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('apartment', sa.String(), nullable=False),
    sa.Column('t1Name', sa.String(), nullable=False),
    sa.Column('t1DOB', sa.Date(), nullable=False),
    sa.Column('t1cellNumber', sa.String(), nullable=False),
    sa.Column('t1email', sa.String(), nullable=False),
    sa.Column('t1employer', sa.String(), nullable=True),
    sa.Column('t1workAddress', sa.String(), nullable=True),
    sa.Column('t1workNumber', sa.Integer(), nullable=True),
    sa.Column('t2Name', sa.String(), nullable=True),
    sa.Column('t2DOB', sa.Date(), nullable=True),
    sa.Column('t2cellNumber', sa.String(), nullable=True),
    sa.Column('t2email', sa.String(), nullable=True),
    sa.Column('t2employer', sa.String(), nullable=True),
    sa.Column('t2workAddress', sa.String(), nullable=True),
    sa.Column('t2workNumber', sa.String(), nullable=True),
    sa.Column('o1name', sa.String(), nullable=True),
    sa.Column('o1age', sa.Integer(), nullable=True),
    sa.Column('o2name', sa.String(), nullable=True),
    sa.Column('o2age', sa.Integer(), nullable=True),
    sa.Column('o3name', sa.String(), nullable=True),
    sa.Column('o3age', sa.Integer(), nullable=True),
    sa.Column('o4name', sa.String(), nullable=True),
    sa.Column('o4age', sa.Integer(), nullable=True),
    sa.Column('o5name', sa.String(), nullable=True),
    sa.Column('o5age', sa.Integer(), nullable=True),
    sa.Column('emergencyName', sa.String(), nullable=False),
    sa.Column('emergencyPhone', sa.String(), nullable=False),
    sa.Column('emergencyAddress', sa.String(), nullable=False),
    sa.Column('t1signature', sa.String(), nullable=False),
    sa.Column('t2signature', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('item', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_receipts')
    op.drop_table('tenant_infos')
    # ### end Alembic commands ###
